/**
 * Catálogo de produtos da Cora: os 2 pães fixos e os 4 especiais rotativos.
 *
 * Morava dentro da constante D em src/App.jsx, o que deixava nome e preço
 * inalcançáveis pro backend (D traz mock de tela e o App importa React). O cron
 * do e-mail de domingo (api/cron/weekly-special.js) precisa de nome, preço e
 * subCopy do especial da semana, e duplicar esses dados criaria uma segunda
 * fonte de verdade pro preço, que já mudou uma vez neste projeto.
 *
 * Módulo puro de propósito: só string e número, sem React e sem import de
 * asset (`img` é path servido de /public). É isso que permite importar daqui
 * de dentro de uma serverless function, mesmo padrão de api/_lib/cutoff.js.
 *
 * Os ids batem com os de src/config/menu.js. `genero` controla a flexão do
 * toast pós-adicionar ("adicionada"/"adicionado") e `subCopy` é a sub-copy
 * emocional do hero da Novidade. Quando o Backoffice nascer, isto vira tabela.
 */
export const PAES = [
    {id:"original",nome:"Pão Original",peso:"~700g",preco:"R$ 30,00",precoNum:30,genero:"m",img:"/images/_original.webp",desc:"O pão do dia a dia. Vai com manteiga no café e com azeite no jantar.",sobre:"Foi com esse pão que tudo começou. Hugo repetiu a receita por anos até chegar num resultado que dava orgulho, e foi nesse processo que a paixão pela panificação se formou. Blend de farinha italiana com um toque de integral brasileira pra ganhar sabor. 24 horas de fermentação, 72% de hidratação.",ingredientes:"Farinha de trigo italiana, água mineral, levain Cora, farinha integral brasileira e sal marinho",subCopy:"O pão que começou tudo.",qtd:1},
    {id:"integral",nome:"Pão Integral",peso:"~700g",preco:"R$ 30,00",precoNum:30,genero:"m",img:"/images/_integral.webp",desc:"A versão integral do Original. Leve, macia, com gergelim na crosta.",sobre:"A versão integral tinha que ser tão versátil quanto o Original. Leve, macia, longe daqueles integrais que parecem tijolo. O processo exige mais cuidado, e o resultado vale. Farinha 100% integral da Fazenda Vargem, um toque de azeite extra virgem que traz maciez, gergelim na crosta. A receita veio quase toda de um curso, com ajustes pra ficar com a cara da Cora. Fermentação com o levain Cora, 77% de hidratação.",ingredientes:"Farinha integral Fazenda Vargem, água mineral, levain Cora, azeite extra virgem, sal marinho e gergelim",subCopy:"Integral leve, todo dia.",qtd:0},
];

export const ROTATIVOS = [
    {id:"multigraos",nome:"Multigrãos",peso:"~620g",preco:"R$ 36,00",precoNum:36,genero:"m",img:"/images/_multigraos.webp",desc:"Seis grãos torrados e escaldados no miolo. Crosta de farelo de aveia. O pão das ocasiões.",sobre:"Receita aprendida com Alex Duarte, do ISPA. Seis grãos diferentes no miolo, crosta de farelo de aveia. O processo de torrar e escaldar os grãos antes de incorporar traz um perfume e uma profundidade de sabor que vale cada mordida. É o pão mais indulgente da Cora, pra uma celebração que pode ser do dia a dia ou de algo especial. Com 110% de hidratação, exige mais atenção do padeiro. Qualquer deslize compromete o resultado.",ingredientes:"Blend de farinhas, água mineral, gergelim branco sem casca, gergelim preto, quinoa, linhaça dourada, semente de girassol, semente de abóbora, farelo de aveia, levain Cora e sal marinho",subCopy:"Pra torrada com abacate, e pra sopa que vira jantar."},
    {id:"focaccia",nome:"Focaccia Genovesa",peso:"~420g",preco:"R$ 28,00",precoNum:28,genero:"f",img:"/images/_focaccia.webp",desc:"Joia da Ligúria. Macia por dentro, dourada por fora. Cebola roxa macerada, azeite infusionado com alecrim e um toque de flor de sal.",sobre:"Joia da culinária da Ligúria, no norte da Itália. A versão autêntica genovesa tem espessura fina, cerca de 2 cm, miolo extremamente macio e crosta dourada e levemente crocante. O segredo está na generosidade do azeite extra virgem e na salmoura que preenche os buraquinhos característicos. A tradição leva alecrim e sal grosso. Na Cora entra também um pouco de cebola roxa. É um pão meio pizza, leve, com cobertura que dá vontade de comer o tabuleiro inteiro. Sai do forno no tabuleiro e vai vendida em pedaços.",ingredientes:"Farinha de trigo italiana, água mineral, azeite extra virgem infusionado com alecrim, levain Cora, cebola roxa, flor de sal e sal marinho",subCopy:"Pra um café da tarde diferente, e pra mesa cheia de gente."},
    {id:"ciabatta",nome:"Ciabatta",peso:"~480g",preco:"R$ 25,00",precoNum:25,genero:"f",img:"/images/_ciabatta.webp",desc:"Miolo cheio de alvéolos, casca fina e crocante. O pão do sanduíche ou da refeição.",sobre:"Ciabatta significa chinelo em italiano, pelo formato achatado e largo. É invenção recente: foi criada em 1982 por Arnaldo Cavallari, em Adria, perto de Veneza. Ele queria um pão italiano que competisse com a baguete francesa nos sanduíches. O segredo das bolhas grandes está na hidratação alta. A massa fica úmida e difícil de manipular, exige técnica e paciência. Blend de farinha italiana com 10% de farinha integral e um fio de azeite. Miolo leve e elástico, casca fina e crocante, com camada generosa de farinha por fora.",ingredientes:"Blend de farinha italiana e farinha integral, água mineral, levain Cora, sal marinho e azeite extra virgem",subCopy:"Pro sanduíche caprichado, e pra limpar o molho do prato."},
    {id:"brioche",nome:"Brioche",peso:"~350g",preco:"R$ 36,00",precoNum:36,genero:"m",img:"/images/_brioche.webp",desc:"Macio, levemente adocicado, com perfume cítrico. Cabe na lancheira da escola e no café da manhã sem pressa.",sobre:"Brioche que junta a tradição francesa com técnica italiana. Blend de farinha italiana com um toque de semola, ovos, manteiga, leite e mel. Açúcar aromatizado com raspas de laranja, limão siciliano e baunilha. Pão leve, com leve doçura e perfume cítrico. Fermentação lenta, 100% levain Cora. Exige atenção constante na temperatura pra não perder o ponto da massa. Hugo desenhou pensando nas crianças, num lanche fácil de mastigar pra escola. Adulto também não resiste.",ingredientes:"Blend de farinha italiana e semola, ovos, manteiga, levain Cora, leite, açúcar, mel, sal marinho, raspas de laranja, raspas de limão siciliano e baunilha",subCopy:"Pro lanche da escola, e pra manhã preguiçosa de domingo."},
];
